const animals= [
  {"name": "aardvark",
  "habitat": "grassland",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/470x370/aardvark_1.jpg",
  "alt": "An aardvark"},
  {"name": "african Elephant",
  "habitat": "grassland",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/470x370/african_bush_elephant12.jpg",
  "alt": "An African Elephant"},
  {"name": "Adelie Penguin",
  "habitat": "polar",
  "type": "bird",
  "src": "https://a-z-animals.com/media/animals/images/180x170/adelie_penguin3.jpg",
  "alt": "An Adelie Penguin"},
  {"name": "African Clawed Frog",
  "habitat": "grassland",
  "type": "amphibian",
  "src": "https://a-z-animals.com/media/animals/images/180x170/african_clawed_frog5.jpg",
  "alt": "An African Clawed Frog"},
  {"name": "African Penguin",
  "habitat": "ocean",
  "type": "bird",
  "src": "https://a-z-animals.com/media/animals/images/470x370/african_penguin.jpg",
  "alt": "An African Penguin"},
  {"name": "African Tree Toad",
  "habitat": "grassland",
  "type": "amphibian",
  "src": "https://a-z-animals.com/media/animals/images/470x370/african_tree_toad.jpg",
  "alt": "An African Tree Toad"},
  {"name": "African Wild Dog",
  "habitat": "grassland",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/african_wild_dog1.jpg",
  "alt": "An African Wild Dog"},
  {"name": "Albatross",
  "habitat": "ocean",
  "type": "bird",
  "src": "https://a-z-animals.com/media/animals/images/180x170/albatross.jpg",
  "alt": "Flying Albatross"},
  {"name": "Aldabra Giant Tortoise",
  "habitat": "grassland",
  "type": "reptile",
  "src": "https://a-z-animals.com/media/animals/images/180x170/aldabra_giant_tortoise2.jpg",
  "alt": "An Aldabra Giant Tortoise"},
  {"name": "Alligator",
  "habitat": "freshwater",
  "type": "reptile",
  "src": "https://a-z-animals.com/media/animals/images/180x170/alligator_8.jpg",
  "alt": "An alligator"},
  {"name": "angelfish",
  "habitat": "ocean",
  "type": "fish",
  "src": "https://www.aqua.org/-/media/Images/blog/2017/Animals/blog-animal-update-freshwater-angelfish-640x800.ashx?la=en&hash=10BD39A5FAB46EECF765BE367657A953E65A591A",
  "alt": "An angelfish"},
  {"name": "ant",
  "habitat": "temperate-forest",
  "type": "invertebrate",
  "src": "https://a-z-animals.com/media/animals/images/180x170/ant1.jpg",
  "alt": "An ant"},
  {"name": "anteater",
  "habitat": "grassland",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/anteater.jpg",
  "alt": "African Anteater"},
  {"name": "Antelope",
  "habitat": "grassland",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/antelope5.jpg",
  "alt": "An antelope"},
  {"name": "Arctic Fox",
  "habitat": "polar",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/arctic_fox9.jpg",
  "alt": "A baby arctic fox"},
  {"name": "Arctic Hare",
  "habitat": "polar",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/arctic_hare4.jpg",
  "alt": "An arctic hare"},
  {"name": "Arctic Wolf",
  "habitat": "polar",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/470x370/arctic_wolf2.jpg",
  "alt": "An arctic wolf"},
  {"name": "Armadillo",
  "habitat": "grassland",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/470x370/armadillo.jpg",
  "alt": "An armadillo"},
  {"name": "Asian Elephant",
  "habitat": "rainforest",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/asian_elephant12.jpg",
  "alt": "Asian Elephant"},
  {"name": "Asiatic Black Bear",
  "habitat": "rainforest",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/asian_black_bear_4.jpg",
  "alt": "Asiatic Black Bear"},
  {"name": "Avocet",
  "habitat": "ocean",
  "type": "bird",
  "src": "https://a-z-animals.com/media/animals/images/470x370/avocet.jpg",
  "alt": "An avocet flying"},
  {"name": "Axolotl",
  "habitat": "freshwater",
  "type": "amphibian",
  "src": "https://a-z-animals.com/media/animals/images/180x170/axolotl1.jpg",
  "alt": "Axolotl in the water"},
  {"name": "Aye Aye",
  "habitat": "rainforest",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/470x370/aye_aye_.jpg",
  "alt": "Aye aye with glowing eyes"},
  {"name": "Baboon",
  "habitat": "grassland",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/baboon1.jpg",
  "alt": "A baboon family"},
  {"name": "Badger",
  "habitat": "temperate-forest",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/470x370/badger2.jpg",
  "alt": "A badger"},
  {"name": "Bandicoot",
  "habitat": "rainforest",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/470x370/bandicoot.jpg",
  "alt": "A bandicoot"},
  {"name": "Barb",
  "habitat": "ocean",
  "type": "fish",
  "src": "https://a-z-animals.com/media/animals/images/180x170/barb.png",
  "alt": "Two Barbs",},
  {"name": "Barn Owl",
  "habitat": "temperate-forest",
  "type": "bird",
  "src": "https://a-z-animals.com/media/animals/images/470x370/barn_owl1.jpg",
  "alt": "A barn owl"},
  {"name": "Barracuda",
  "habitat": "ocean",
  "type": "fish",
  "src": "https://a-z-animals.com/media/animals/images/470x370/barracuda4.jpg",
  "alt": "A barracuda"},
  {"name": "Basking Shark",
  "habitat": "ocean",
  "type": "fish",
  "src": "https://a-z-animals.com/media/animals/images/470x370/basking_shark.jpg",
  "alt": "A basking shark"},
  {"name": "Bat",
  "habitat": "temperate-forest",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/bat2.jpg",
  "alt": "A hanging bat"},
  {"name": "Bearded Dragon",
  "habitat": "grassland",
  "type": "reptile",
  "src": "https://a-z-animals.com/media/animals/images/180x170/bearded_dragon4.jpg",
  "alt": "A bearded dragon"},
  {"name": "Beaver",
  "habitat": "temperate-forest",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/beaver8.jpg",
  "alt": "A beaver"},
  {"name": "Beetle",
  "habitat": "temperate-forest",
  "type": "invertebrate",
  "src": "https://a-z-animals.com/media/animals/images/180x170/beetle1.jpg",
  "alt": "A beetle"},
  {"name": "Bengal Tiger",
  "habitat": "rainforest",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/bengal_tiger3.jpg",
  "alt": "A bengal tiger"},
  {"name": "Binturong",
  "habitat": "rainforest",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/binturong_10.jpg",
  "alt": "A binturong"},
  {"name": "Birds Of Paradise",
  "habitat": "rainforest",
  "type": "bird",
  "src": "https://a-z-animals.com/media/animals/images/180x170/birds_of_paradise1.jpg",
  "alt": "A bird of paradise"},
  {"name": "Bison",
  "habitat": "temperate-forest",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/bison.jpg",
  "alt": "A bison"},
  {"name": "Black Bear",
  "habitat": "temperate-forest",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/black_bear6.jpg",
  "alt": "A black bear"},
  {"name": "Black Rhinoceros",
  "habitat": "grassland",
  "type": "mammal",
  "src": "https://a-z-animals.com/media/animals/images/180x170/black_rhinoceros2.jpg",
  "alt": "A black rhinoceros badger"},
  {"name": "Black Widow Spider",
  "habitat": "temperate-forest",
  "type": "invertebrate",
  "src": "https://a-z-animals.com/media/animals/images/180x170/black_widow_spider3.jpg",
  "alt": "A black widow spider"},
  {"name": "Blue Whale",
  "habitat": "ocean",
  "type": "mammal",
  "src": "https://res.cloudinary.com/dk-find-out/image/upload/q_80,w_1920,f_auto/MA_00925211_gwnvzd.jpg",
  "alt": "A blue whale"},
  {"name": "Bonobo",
  "habitat": "rainforest",
  "type": "mammal",
  "src": "https://c402277.ssl.cf1.rackcdn.com/photos/15180/images/hero_small/_MA_8993.JPG?1518449593",
  "alt": "A bonobo"},
  {"name": "Orangutan",
  "habitat": "rainforest",
  "type": "mammal",
  "src": "https://www.lifegate.com/app/uploads/Oranghi-nella-foresta.jpg",
  "alt": "An orangutan and her baby"},
  {"name": "Borneo Elephant",
  "habitat": "rainforest",
  "type": "mammal",
  "src": "https://www.oregonzoo.org/sites/default/files/styles/article-full/public/2014/09/24/H_Borneo-elephants-HUTAN-KOCP.jpg?itok=Agy6QqdV",
  "alt": "Borneo elephants"},
  {"name": "Bottle Nosed Dolphin",
  "habitat": "ocean",
  "type": "mammal",
  "src": "https://www.illumina.com/content/dam/illumina-marketing/images/company/featured-articles/bottlenose_dolphin.png",
  "alt": "A bottlenose dolphin"},
  {"name": "Brown Bear",
  "habitat": "temperate-forest",
  "type": "mammal",
  "src": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Kamchatka_Brown_Bear_near_Dvuhyurtochnoe_on_2015-07-23.jpg",
  "alt": "A brown bear"},
  {"name": "Budgerigar",
  "habitat": "grassland",
  "type": "mammal",
  "src": "https://www.thesprucepets.com/thmb/PQADJeGVONTlPHLkC-u6cNeMAME=/3696x2448/filters:no_upscale():max_bytes(150000):strip_icc()/close-up-of-budgerigars-perching-on-branch-909976322-5b4bf18746e0fb005bc62377.jpg",
  "alt": "Four budgerigars"},
  {"name": "Buffalo",
  "habitat": "grassland",
  "type": "mammal",
  "src": "https://images.unsplash.com/photo-1508605375977-9fe795aea86a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
  "alt": "A buffalo"},
  {"name": "Bull Shark",
  "habitat": "ocean",
  "type": "fish",
  "src": "https://static1.squarespace.com/static/54362ecbe4b0179b57ed31c7/t/5987fb167131a5259cd7e159/1502083878526/IMG_6217_resize.jpg",
  "alt": "A bull shark"},
  {"name": "Bullfrog",
  "habitat": "freshwater",
  "type": "amphibian",
  "src": "http://rivista-cdn.reptilesmagazine.com/american-bullfrog-shutterstock_53341660.jpg?ver=1532104951",
  "alt": "A bullfrog"},
  {"name": "Bumblebee",
  "habitat": "temperate-forest",
  "type": "invertebrate",
  "src": "https://a-z-animals.com/media/animals/images/470x370/bumble_bee4.jpg",
  "alt": "A bumblebee"},
  {"name": "Burrowing Frog",
  "habitat": "freshwater",
  "type": "amphibian",
  "src": "https://a-z-animals.com/media/animals/images/470x370/burrowing_frog2.jpg",
  "alt": "A burrowing frog"},
  {"name": "Butterfly",
  "habitat": "temperate-forest",
  "type": "invertebrate",
  "src": "https://a-z-animals.com/media/animals/images/180x170/butterfly1.jpg",
  "alt": "A butterfly"},
  {"name": "Butterfly Fish",
  "habitat": "ocean",
  "type": "fish",
  "src": "https://a-z-animals.com/media/animals/images/180x170/butterfly_fish6.jpg",
  "alt": "A butterfly fish"},
]